artifact_location: file:///Users/victorbonilla/Documents/MIAD/1er Semestre/2do Ciclo/Machine
  Learning/Semana 1/Proyecto_DSA/notebooks/mlruns_victor/496775632379775562
creation_time: 1762568158408
experiment_id: '496775632379775562'
last_update_time: 1762568158408
lifecycle_stage: active
name: Proyecto_DSA_Victor
