artifact_uri: file:///Users/victorbonilla/Documents/MIAD/1er Semestre/2do Ciclo/Machine
  Learning/Semana 1/Proyecto_DSA/notebooks/mlruns_victor/496775632379775562/e9a6e3d8a2044edcbb73ac975e86fd75/artifacts
end_time: 1762569019722
entry_point_name: ''
experiment_id: '496775632379775562'
lifecycle_stage: active
run_id: e9a6e3d8a2044edcbb73ac975e86fd75
run_name: GradientBoostingRegressor_EmptyStopTime
source_name: ''
source_type: 4
source_version: ''
start_time: 1762569017715
status: 3
tags: []
user_id: victorbonilla
