artifact_uri: file:///Users/victorbonilla/Documents/MIAD/1er Semestre/2do Ciclo/Machine
  Learning/Semana 1/Proyecto_DSA/notebooks/mlruns_victor/496775632379775562/4425927a00034f7f81b2f33a453267dc/artifacts
end_time: 1762568160955
entry_point_name: ''
experiment_id: '496775632379775562'
lifecycle_stage: active
run_id: 4425927a00034f7f81b2f33a453267dc
run_name: reg_EmptyStopTime
source_name: ''
source_type: 4
source_version: ''
start_time: 1762568158410
status: 3
tags: []
user_id: victorbonilla
