artifact_uri: file:///Users/victorbonilla/Documents/MIAD/1er Semestre/2do Ciclo/Machine
  Learning/Semana 1/Proyecto_DSA/notebooks/mlruns_victor/496775632379775562/07a263437d4f46548aff192460f27e3e/artifacts
end_time: 1762568309991
entry_point_name: ''
experiment_id: '496775632379775562'
lifecycle_stage: active
run_id: 07a263437d4f46548aff192460f27e3e
run_name: reg_EmptyStopTime
source_name: ''
source_type: 4
source_version: ''
start_time: 1762568307493
status: 3
tags: []
user_id: victorbonilla
