artifact_uri: file:///Users/victorbonilla/Documents/MIAD/1er Semestre/2do Ciclo/Machine
  Learning/Semana 1/Proyecto_DSA/notebooks/mlruns_victor/496775632379775562/c15eb8a45565415f955692e11a22956f/artifacts
end_time: 1762568314249
entry_point_name: ''
experiment_id: '496775632379775562'
lifecycle_stage: active
run_id: c15eb8a45565415f955692e11a22956f
run_name: clf_EfficientCycle
source_name: ''
source_type: 4
source_version: ''
start_time: 1762568312337
status: 3
tags: []
user_id: victorbonilla
