artifact_location: file:///Users/victorbonilla/Documents/MIAD/1er Semestre/2do Ciclo/Machine
  Learning/Semana 1/Proyecto_DSA/notebooks/mlruns_victor/496775632379775562/models/m-eda58bd113bd4c3b82a54abc3d8a58be/artifacts
creation_timestamp: 1762568279951
experiment_id: '496775632379775562'
last_updated_timestamp: 1762568281726
model_id: m-eda58bd113bd4c3b82a54abc3d8a58be
model_type: null
name: model_LoadStopTime
source_run_id: 45edc7039bda47348862a3fd15fbbd07
status: 2
status_message: null
